### ISSUE TITLE
tox-factor doesn't work with latest version of tox

### ISSUE THREAD

**Issue by TheFriendlyCoder** [rpkilby/tox-factor#8]
Tox v3.14.1 just got released a few days ago and now the tox-factor plugin no longer works. Based on my initial assessment it looks like a global property defined internally within tox was renamed in the latest release and tox-factor was leveraging that property for some conditional logic under the hood. The error looks like this:

> ..site-packages/tox_factor/hooks.py", line 4, in <module>
>    from tox.config.parallel import ENV_VAR_KEY as TOX_PARALLEL_ENV
> ImportError: cannot import name 'ENV_VAR_KEY'

This needs to be fixed

**Comment by TheFriendlyCoder** [comment]
NOTE: The offending changes in tox look to be located here: https://github.com/tox-dev/tox/commit/0a44dccb5bcc6c133c622d65e143c83a652c5fa9
